hpMvc/Controllers/AdminBackDoorController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using hpMvc.Models;
using hpMvc.DataBase;
using hpMvc.Infrastructure.Logging;
using Telerik.Web.Mvc;

namespace hpMvc.Controllers
{
    [Authorize(Roles = "Admin")] 
    public class AdminBackDoorController : Controller
    {
        NLogger nlogger = new NLogger();

        [Telerik.Web.Mvc.PopulateSiteMap(SiteMapName = "adminbackdoor", ViewDataKey = "adminbackdoor")]
        public ActionResult Index()
        {
            List<Site> sites = new List<Site>();
                        
            sites = DbUtils.GetSitesActive();
            if (sites.Count == 0)
                throw new Exception("There was an error retreiving the sites list from the database");
            sites.Insert(0, new Site { ID = 0, Name = "Select a site", SiteID = "" });
            ViewBag.Sites = new SelectList(sites, "ID", "Name");

            nlogger.LogInfo("Admin Backdoor Index - user: " + HttpContext.User.Identity.Name);

            List<MembershipUser> users = new List<MembershipUser>();
            users = AccountUtils.GetAllUsers();
            
            ViewBag.Users = new SelectList(users, "UserName", "UserName");
            if (!SiteMapManager.SiteMaps.ContainsKey("adminbackdoor"))
            {
                SiteMapManager.SiteMaps.Register<XmlSiteMap>("adminbackdoor", sitmap => sitmap.LoadFrom("~/adminbackdoor.sitemap"));
            }
            return View();
        }

    }
}

hpMvc/Controllers/DccController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using hpMvc.DataBase;
using System.Web.Helpers;
using hpMvc.Models;

namespace hpMvc.Controllers
{
    [Authorize(Roles = "Admin,DCC")]
    public class DccController : Controller
    {
        //
        // GET: /Dcc/

        public ActionResult Index()
        {
            return View();
        }
                
        public ActionResult RandomizedStudies(string siteID)
        {
            List<Site> sites = new List<Site>();

            sites = DbUtils.GetSitesActive();
            if (sites.Count == 0)
                throw new Exception("There was an error retreiving the sites list from the database");
            sites.Insert(0, new Site { ID = 0, Name = "Select a site", SiteID = "" });
            ViewBag.Sites = new SelectList(sites, "ID", "Name");

            List<Randomization> list = null;
            if (string.IsNullOrEmpty(siteID))
            {
                list = DbUtils.GetAllRandomizedStudies();
            }
            else
            {
                list = DbUtils.GetSiteRandomizedStudies(int.Parse(siteID));
            }
                        
            return View(list);
        }

        public JsonResult GetSiteRandomizedStudies(string siteID)
        {
            var list = DbUtils.GetSiteRandomizedStudies(int.Parse(siteID));
            var grid = new WebGrid(list, defaultSort: "Number", rowsPerPage: 50);
            var htmlString = grid.GetHtml(tableStyle:"webgrid",
                            columns:grid.Columns(
                            grid.Column("SiteName", header:"Site"),
                            grid.Column("Number"),
                            grid.Column("StudyID", header: "Study  ID"),
                            grid.Column("Arm"),
                            grid.Column("DateRandomized", header:"Date Randomized", format: x => x.DateRandomized.ToString("MM/dd/yyyy hh:mm tt"))));

            return Json(new { Data = htmlString.ToHtmlString(), Count = list.Count }, JsonRequestBehavior.AllowGet);
        }
    }
}

hpMvc/Views/AdminBackDoor/Index.cshtml
@using Telerik.Web.Mvc.UI
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "Admin", FormMethod.Post))
{
    <div id="divSideBar2">
        @(Html.Telerik().Menu()
            .Orientation(MenuOrientation.Vertical)
            .Name("MenuAB")            
            .BindTo("adminbackdoor", (item, node) =>
       {
           string roles = node.Attributes["role"] as string;
           if (roles == "nurse")
               item.Visible = false;
           if (node.Attributes["name"] != null)
               item.RouteValues.Add("name", node.Attributes["name"]);
           if (node.Attributes["fileName"] != null)
               item.RouteValues.Add("fileName", node.Attributes["fileName"]);
           if (node.Attributes["folder"] != null)
               item.RouteValues.Add("folder", node.Attributes["folder"]);
           if (node.Attributes["class"] != null)
               item.HtmlAttributes.Add("class", node.Attributes["class"]);
           if (node.Attributes["id"] != null)
               item.HtmlAttributes.Add("id", node.Attributes["id"]);

       }))
        @*<ul>
            <li>@Html.ActionLink("Add new user", "AddUser", "Admin")</li>
            <li>@Html.ActionLink("Manage user roles", "ManageUserRoles", new{controller = "Admin"}, new { @class = "aLnkClick" })</li>
            <li>@Html.ActionLink("Reset user password", "ResetUserPassword", new { controller = "Admin" }, new { @class = "aLnkClick" })</li>
            <li>@Html.RouteLink("Show Study IDs Not Randomized", new { Controller = "Coordinator", Action = "StudyIdsNotRandomized" })</li>            
            <li>@Html.ActionLink("Show Randomized Studies", "RandomizedStudies", "Dcc")</li>
            <li>@Html.ActionLink("Show Web Logs", "WebLogs")</li>
            <li>@Html.ActionLink("Download a Saved Spreadsheet", "GetSavedChecks")</li>
            <li>@Html.RouteLink("Upload CHECKS Template", new { controller="FileManager", Action = "TemplateUpload" })</li>
            <li>@Html.ActionLink("Broadcast Email", "BroadcastEmail")</li>
            <li>@Html.ActionLink("Show All Users", "ShowUsers")</li>
            
            @if (@ViewBag.Role == "Admin")
            { 
                <li>@Html.ActionLink("Manage Roles", "ManageRoles")</li>
                <li>@Html.ActionLink("Delete user", "DeleteUser", new { controller = "Admin" }, new { @id = "deleteUser" })</li>
                
            }
            <li>@Html.ActionLink("Send Test Email", "TestEmail")</li>
        </ul>*@
    </div>

    <div id="div1Col">
        <span>Select a site:&nbsp;</span> @Html.DropDownList("Sites")
        <br /><br />
        
        <span>Select a user: </span>&nbsp; @Html.DropDownList("Users")
        <br /><br />
            
    </div>
    <div id="div2Col">
        <table class="tblRoles">
            <thead>            
                <tr>
                    <th>
                        Roles for selected user            
                    </th>            
                </tr>
            </thead>
            <tbody>
                    
            </tbody>        
        </table>       
    </div>
}    
    <link href="@Url.Content("~/Content/Admin.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/UserManagement.js")" type="text/javascript"></script>
    @(Html.Telerik().StyleSheetRegistrar().DefaultGroup(group => group.Add("telerik.common.css").Add("telerik.office2010blue.css")))
    @(Html.Telerik().ScriptRegistrar().jQuery(false))



