hpMvc/Controllers/CalorieCalcController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using hpMvc.DataBase;
using hpMvc.Helpers;
using hpMvc.Models;

namespace hpMvc.Controllers
{
    [Authorize]
    public class CalorieCalcController : Controller
    {
        //
        // GET: /CalorieCalc/

        public ActionResult EditSelect()
        {
            int siteId = DbUtils.GetSiteidIdForUser(User.Identity.Name);
            var idnl = CalorieCalc.GetCalStudySelectList(siteId);
            idnl.Insert(0, new IDandName { ID = 0, Name = "select" });
            
            ViewBag.CalStudyList = new SelectList(idnl, "ID", "Name");

            return View();
        }

        [HttpPost]
        public JsonResult GetCalcWeight(string studyId)
        {
            int id = int.Parse(studyId);
            double weight = CalorieCalc.GetCalcWeight(id);
            return Json(weight);
        }

        [HttpPost]
        public JsonResult GetStudyDay(string studyId, string calcDate)
        {
            int id = int.Parse(studyId);
            int day = CalorieCalc.GetStudyDay(id, DateTime.Parse(calcDate));
            return Json(day);
        }

        [HttpPost]
        public JsonResult GetCalcDates(string studyId)
        {
            List<IDandName> idnl = CalorieCalc.GetCalCalcDates(int.Parse(studyId));
            idnl.Insert(0, new IDandName { ID = 0, Name = "select" });
            return Json(idnl);
        }

        [HttpPost]
        public JsonResult GetStudyInfo(string calStudyId)
        {
            var csi = CalorieCalc.GetCalStudyInfo(calStudyId);
            return Json(csi);
        }

        public ActionResult Index()
        {
            int siteId = DbUtils.GetSiteidIdForUser(User.Identity.Name);
            var studyList = DbUtils.GetRandomizedStudiesForSite(siteId);
            studyList.Insert(0, new IDandStudyID { ID = 0, StudyID = "Select Study" });
            ViewBag.StudyList = new SelectList(studyList, "ID", "StudyID");
            ViewBag.StudyDay = "";

            var dc1 = CalorieCalc.GetDextroseConcentrations();
            var dc = new DextroseConcentration{ ID=0, Concentration=" Dextrose % ", Kcal_ml=0};
            dc1.Insert(0, dc);

            ViewBag.DexCons1 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons2 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons3 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons4 = new SelectList(dc1, "Kcal_ml", "Concentration");
            
            List<IDandName> sl = DbUtils.GetLookupItems("FormulaList");
            if (sl.Count == 0)
                throw new Exception("There was an error retrieving the FormulaList from the database");
            sl.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.FormulaList = new SelectList(sl, "ID", "Name");

            List<IDandName> sl2 = DbUtils.GetLookupItems("AdditiveList");
            if (sl2.Count == 0)
                throw new Exception("There was an error retrieving the Additives from the database");
            sl2.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.AdditiveList = new SelectList(sl2, "ID", "Name");

            List<IDandName> sl3 = DbUtils.GetLookupItems("Units");
            if (sl3.Count == 0)
                throw new Exception("There was an error retrieving the Units from the database");
            sl3.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.Units = new SelectList(sl3, "ID", "Name");
            
            return View();
        }
        
        public ActionResult Edit(CalStudyInfo csi)
        {
            
            //DateTime date = DateTime.Parse( csi.CalcDate);

            ViewBag.Mode = "Edit";
            ViewBag.Weight = csi.Weight.ToString();
            ViewBag.CalcDate = csi.CalcDate;
            ViewBag.CalStudyID = csi.Id;
            ViewBag.Hours = csi.Hours;
            int studyDay = CalorieCalc.GetStudyDay(csi.StudyId, DateTime.Parse(csi.CalcDate));
            ViewBag.StudyDay = studyDay.ToString();

            int siteId = DbUtils.GetSiteidIdForUser(User.Identity.Name);
            //todo remove for production
            //if (siteId == 0)
            //    siteId = 1;

            var studyList = DbUtils.GetRandomizedStudiesForSite(siteId);
            studyList.Insert(0, new IDandStudyID { ID = 0, StudyID = "Select Study" });
            ViewBag.StudyList = new SelectList(studyList, "ID", "StudyID",csi.StudyId);

            var dc1 = CalorieCalc.GetDextroseConcentrations();
            var dc = new DextroseConcentration { ID = 0, Concentration = " Dextrose % ", Kcal_ml = 0 };
            dc1.Insert(0, dc);

            ViewBag.DexCons1 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons2 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons3 = new SelectList(dc1, "Kcal_ml", "Concentration");
            ViewBag.DexCons4 = new SelectList(dc1, "Kcal_ml", "Concentration");

            List<IDandName> sl = DbUtils.GetLookupItems("FormulaList");
            if (sl.Count == 0)
                throw new Exception("There was an error retrieving the FormulaList from the database");
            sl.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.FormulaList = new SelectList(sl, "ID", "Name");

            List<IDandName> sl2 = DbUtils.GetLookupItems("AdditiveList");
            if (sl2.Count == 0)
                throw new Exception("There was an error retrieving the Additives from the database");
            sl2.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.AdditiveList = new SelectList(sl2, "ID", "Name");

            List<IDandName> sl3 = DbUtils.GetLookupItems("Units");
            if (sl3.Count == 0)
                throw new Exception("There was an error retrieving the Units from the database");
            sl3.Insert(0, new IDandName { ID = 0, Name = "Select" });
            ViewBag.Units = new SelectList(sl3, "ID", "Name");

            return View("Index");
        }

        public JsonResult GetAllData(string studyID, string calcDate)
        {
            var cad = new CalAllData();
            var cicl = new List<CalInfuseColumn>();

            int calStudyID = CalorieCalc.GetCalStudyId(studyID, calcDate);
            
            var cidl = CalorieCalc.GetCalInfusionsDexData(calStudyID);

            foreach(var cid in cidl)
            {
                List<CalInfusionVol> civl = CalorieCalc.GetCalInfusionsVolData(cid.ID);
                int[] volumes = new int[civl.Count];
                int index = 0;
                var cic = new CalInfuseColumn();

                foreach (var civ in civl)
                {
                    
                    cic.DexValue = cid.DexVal;
                    volumes[index] = civ.Volume;
                    index++;
                }
                cic.Volumes = volumes;
                cicl.Add(cic);
            }

            var cpl = CalorieCalc.GetCalParenteralsData(calStudyID);
            var cel = CalorieCalc.GetCalEnteralsData(calStudyID);
            var cal = CalorieCalc.GetCalAdditivesData(calStudyID);
            var con = CalorieCalc.GetCalOtherNutrition(calStudyID);


            cad.calInfusionCol = cicl;
            cad.calParenterals = cpl;
            cad.calEnterals = cel;
            cad.calAdditives = cal;
            cad.calOtherNutrition = con;

            return Json(cad);
        }

        
        public JsonResult GetFormulaData()
        {
            var efl = CalorieCalc.GetFormulaList();
            return Json(efl);
        }

        public JsonResult GetAdditiveData()
        {
            var addl = CalorieCalc.GetAdditiveList();
            return Json(addl);
        }

        public JsonResult AddNewFormula([Bind(Exclude = "ID")]EnteralFormula ef)
        {
            DTO dto = new DTO();
            if (ModelState.IsValid)
            {
                if (CalorieCalc.IsFormulaNameDuplicate(ef.Name) == 1)
                {
                    dto.ReturnValue = 0;
                    dto.Message = ef.Name + " is already in the list!";
                }
                else
                {
                    dto = CalorieCalc.AddFormula(ef);

                    var siteId = DbUtils.GetSiteidIdForUser(User.Identity.Name);
                    var staff = NotificationUtils.GetStaffForEvent(4, siteId);

                    string siteName = DbUtils.GetSiteNameForUser(User.Identity.Name);

                    var u = new UrlHelper(this.Request.RequestContext);
                    string url = "http://" + this.Request.Url.Host +
                                 u.RouteUrl("Default", new {Controller = "Account", Action = "Logon"});

                    Utility.SendFormulaAddeddMail(staff.ToArray(), null, ef, User.Identity.Name, siteName, Server, url);
                }

                dto.Bag = ef;
                return Json(dto);
            }
            else
            {
                return null;
            }
        }

        public JsonResult AddNewAdditive([Bind(Exclude = "ID")]Additive add)
        {
            if (ModelState.IsValid)
            {
                DTO dto = new DTO();

                if (CalorieCalc.IsAdditiveNameDuplicate(add.Name) == 1)
                {
                    dto.ReturnValue = 0;
                    dto.Message = add.Name + " is already in the list!";
                }
                else
                {
                    dto = CalorieCalc.AddAdditive(add);

                    var siteId = DbUtils.GetSiteidIdForUser(User.Identity.Name);

hpMvc/Views/CalorieCalc/AdditiveConfirmation.cshtml
@model hpMvc.Models.Additive

@{
    ViewBag.Title = "Additive Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Additive <strong>@Model.Name</strong> has been updated.</h2>

<div>
    @Html.ActionLink("Back to additive list", "AdditiveList")
</div>

hpMvc/Views/CalorieCalc/AdditiveDetails.cshtml
@using hpMvc.Models
@model hpMvc.Models.Additive

@{
    ViewBag.Title = "Additive Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style rel="stylesheet" type="text/css" >
    fieldset {
        line-height: 25px;
    }
    .lbleditor {
        width: 160px;
        display: inline-block;
    }
    .col2 
    {
        display: inline-block;
        margin-left: 5px;
    }
    .text-box {
        width: 250px;
    }
    .underline {
        text-decoration: underline; 
    }
</style>

<h2>Additive Details for @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
    <input type="hidden" id="ID" name="ID" value='@Model.ID'/>
    
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Formula Details</legend>
        <div>
            <span class="lbleditor">Formula Name:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.Name)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">kCal per unit:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.Kcal_unit)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">Protein % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.ProteinKcal)
                @Html.ValidationMessageFor(model => model.ProteinKcal) 
            </span>
        </div>
        
        <div>
            <span class="lbleditor">CHO % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.ChoKcal)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">Lipid % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.LipidKcal)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">Unit:</span>
            <span class="col2">
                @Html.DropDownListFor(model => model.Unit, new SelectList(Model.Units, "ID", "Name")) 
            </span>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to additive list", "AdditiveList")
</div>

hpMvc/Views/CalorieCalc/AdditiveList.cshtml
@model List<hpMvc.Models.Additive>
@{
    ViewBag.Title = "Additive List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    Additive List</h2>
<div>
    @{
 
        var grid = new WebGrid(Model, defaultSort: "SiteId", rowsPerPage: 50);
        
    }
    @if (@ViewBag.Role == "Admin")
    {
        @grid.GetHtml(
         tableStyle: "webgrid", headerStyle: "header", alternatingRowStyle: "alt",
         columns: grid.Columns(
             grid.Column("ID", header: "Internal Id"),
             grid.Column("Name", header: "Additive Name", format: @<text>@Html.ActionLink((string)item.Name, "AdditiveDetails", "CalorieCalc", new { id = item.ID }, null)</text>),
             grid.Column("Kcal_unit", header: "kCal per unit", format: (item) => string.Format("{0:N}", item.Kcal_unit)),
             grid.Column("ProteinKcal", header: "Protein % of kcal"),
             grid.Column("ChoKcal", header: "CHO % of kcal"),
             grid.Column("LipidKcal", header: "Lipid % of kcal"),
             grid.Column("UnitName", header: "Unit")
             ))
    }
    else
    {
        @grid.GetHtml(
         tableStyle: "webgrid", headerStyle: "header", alternatingRowStyle: "alt",
         columns: grid.Columns(
             grid.Column("ID", header: "Internal Id"),
             grid.Column("Name", header: "Additive Name"),
             grid.Column("Kcal_unit", header: "kCal per unit", format: (item) => string.Format("{0:N}", item.Kcal_unit)),
             grid.Column("ProteinKcal", header: "Protein % of kcal"),
             grid.Column("ChoKcal", header: "CHO % of kcal"),
             grid.Column("LipidKcal", header: "Lipid % of kcal"),
             grid.Column("UnitName", header: "Unit")
             ))

    }
</div>
<link href="@Url.Content("~/Content/webgrid.css")" rel="stylesheet" type="text/css" />

hpMvc/Views/CalorieCalc/EditSelect.cshtml
@{
    ViewBag.Title = "EditSelect";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Correct Existing Caloric Entry</h2>
<p>
    Select a the study id and date then click submit.
</p>
Study ID: &nbsp;@Html.DropDownList("CalStudyList")
<br />
Date: &nbsp; <select id="calcDates"></select>
<br />
<br />
<input type="button" value="Submit" id="btnSubmit"/>

<script src="@Url.Content("~/Scripts/calCalcEditSelect.js")" type="text/javascript"></script>

hpMvc/Views/CalorieCalc/FormulaConfirmation.cshtml
@model hpMvc.Models.EnteralFormula
@{
    ViewBag.Title = "Formula Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Formula <strong>@Model.Name</strong> has been updated.</h3>

<div>
    @Html.ActionLink("Back to formula list", "FormulaList")
</div>

hpMvc/Views/CalorieCalc/FormulaDetails.cshtml
@model hpMvc.Models.EnteralFormula

@{
    ViewBag.Title = "Formula Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style rel="stylesheet" type="text/css" >
    fieldset {
        line-height: 25px;
    }
    .lbleditor {
        width: 160px;
        display: inline-block;
    }
    .col2 
    {
        display: inline-block;
        margin-left: 5px;
    }
    .text-box {
        width: 250px;
    }
    .underline {
        text-decoration: underline; 
    }
</style>

<h2>Formula Details for @Html.DisplayFor(model => model.Name)</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    <input type="hidden" id="ID" name="ID" value='@Model.ID'/>
    
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Formula Details</legend>
        <div>
            <span class="lbleditor">Formula Name:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.Name)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">kCal per unit:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.Kcal_ml)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">Protein % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.ProteinKcal)
                @Html.ValidationMessageFor(model => model.ProteinKcal) 
            </span>
        </div>
        
        <div>
            <span class="lbleditor">CHO % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.ChoKcal)
            </span>
        </div>
        
        <div>
            <span class="lbleditor">Lipid % of kcal:</span>
            <span class="col2"> 
                @Html.EditorFor(model => model.LipidKcal)
            </span>
        </div>
        
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to formula list", "FormulaList")
</div>

hpMvc/Views/CalorieCalc/FormulaList.cshtml
@model List<hpMvc.Models.EnteralFormula>

@{
    ViewBag.Title = "Formula List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Formula List</h2>

<div>
    @{
 
        var grid = new WebGrid(Model, defaultSort: "SiteId", rowsPerPage: 50);
        
    }
 
    @if (@ViewBag.Role == "Admin")
    {
        @grid.GetHtml(
            tableStyle: "webgrid", headerStyle: "header", alternatingRowStyle: "alt",
            columns: grid.Columns(
                grid.Column("ID", header: "Internal Id"),
                grid.Column("Name", header: "Formula Name", format: @<text>@Html.ActionLink((string) item.Name, "FormulaDetails", "CalorieCalc", new {id = item.ID}, null)</text>),
                grid.Column("Kcal_ml", header: "kCal per unit", format: (item) => string.Format("{0:N}", item.Kcal_ml)),
                grid.Column("ProteinKcal", header: "Protein % of kcal"),
                grid.Column("ChoKcal", header: "CHO % of kcal"),
                grid.Column("LipidKcal", header: "Lipid % of kcal")
                ))  
    }
    else
    {
        @grid.GetHtml(
            tableStyle: "webgrid", headerStyle: "header", alternatingRowStyle: "alt",
            columns: grid.Columns(
                grid.Column("ID", header: "Internal Id"),
                grid.Column("Name", header: "Formula Name"),
                grid.Column("Kcal_ml", header: "kCal per unit", format: (item) => string.Format("{0:N}", item.Kcal_ml)),
                grid.Column("ProteinKcal", header: "Protein % of kcal"),
                grid.Column("ChoKcal", header: "CHO % of kcal"),
                grid.Column("LipidKcal", header: "Lipid % of kcal")
                ))
    }
</div>
<link href="@Url.Content("~/Content/webgrid.css")" rel="stylesheet" type="text/css" />